import { Navigate, Route, Routes } from 'react-router-dom';
import MainLayout from '@/app/layouts/MainLayout';import AuthGuard from '@/app/guards/AuthGuard';
import LoginPage from '@/pages/auth/LoginPage';import DashboardPage from '@/pages/dashboard/IndexPage';
import LeadsListPage from '@/pages/leads/ListPage';import LeadsDetailPage from '@/pages/leads/DetailPage';import LeadsAssignPage from '@/pages/leads/AssignPage';import LeadsFollowPage from '@/pages/leads/FollowPage';
import StudentsListPage from '@/pages/students/ListPage';import StudentsDetailPage from '@/pages/students/DetailPage';
import ApplicationsKanbanPage from '@/pages/applications/KanbanPage';import ApplicationsDetailPage from '@/pages/applications/DetailPage';import MaterialsPage from '@/pages/applications/MaterialsPage';import OffersPage from '@/pages/applications/OffersPage';import VisaPage from '@/pages/applications/VisaPage';
import ArticlesPage from '@/pages/cms/ArticlesPage';import CasesPage from '@/pages/cms/CasesPage';import LibraryPage from '@/pages/knowledge/LibraryPage';import TasksPage from '@/pages/messages/TasksPage';
import ReportsOverviewPage from '@/pages/reports/OverviewPage';import ReportsLeadsPage from '@/pages/reports/LeadsPage';
import UsersPage from '@/pages/settings/UsersPage';import RolesPage from '@/pages/settings/RolesPage';import DictsPage from '@/pages/settings/DictsPage';import LogsPage from '@/pages/settings/LogsPage';
import E403 from '@/pages/errors/403';import E404 from '@/pages/errors/404';
export default function AppRouter(){return <Routes><Route path='/login' element={<LoginPage/>}/><Route path='/' element={<AuthGuard><MainLayout/></AuthGuard>}><Route index element={<Navigate to='/dashboard'/>}/><Route path='dashboard' element={<DashboardPage/>}/><Route path='leads/list' element={<LeadsListPage/>}/><Route path='leads/detail/:id' element={<LeadsDetailPage/>}/><Route path='leads/assign' element={<LeadsAssignPage/>}/><Route path='leads/follow' element={<LeadsFollowPage/>}/><Route path='students/list' element={<StudentsListPage/>}/><Route path='students/detail/:id' element={<StudentsDetailPage/>}/><Route path='applications/kanban' element={<ApplicationsKanbanPage/>}/><Route path='applications/detail/:id' element={<ApplicationsDetailPage/>}/><Route path='applications/materials' element={<MaterialsPage/>}/><Route path='applications/offers' element={<OffersPage/>}/><Route path='applications/visa' element={<VisaPage/>}/><Route path='cms/articles' element={<ArticlesPage/>}/><Route path='cms/cases' element={<CasesPage/>}/><Route path='knowledge/library' element={<LibraryPage/>}/><Route path='messages/tasks' element={<TasksPage/>}/><Route path='reports/overview' element={<ReportsOverviewPage/>}/><Route path='reports/leads' element={<ReportsLeadsPage/>}/><Route path='settings/users' element={<UsersPage/>}/><Route path='settings/roles' element={<RolesPage/>}/><Route path='settings/dicts' element={<DictsPage/>}/><Route path='settings/logs' element={<LogsPage/>}/></Route><Route path='/403' element={<E403/>}/><Route path='*' element={<E404/>}/></Routes>}
