import { Button, Card, Col, Descriptions, Form, Input, Row, Select, Space, Switch, Tabs, Tag, Timeline } from 'antd';
import { useLocation, useParams } from 'react-router-dom';
import { PageHeader } from '@/components';
import { dictItems, logs, roles, users } from '@/mock/settings';
import { useEnterpriseActions } from '@/hooks/useEnterpriseActions';

export default function SettingsDetailPage(){
  const params = useParams(); const location = useLocation(); const type = location.pathname.includes('data-permission') ? 'dataPermission' : (params.type || 'user'); const mode = location.pathname.includes('data-permission') ? 'permission' : (params.mode || 'detail'); const id = params.id || 'U01'; const {openAction, contextHolder}=useEnterpriseActions('系统设置');
  const dict = Object.values(dictItems).flat().find((i:any)=>i.id===id) || Object.values(dictItems).flat()[0]; const data:any = type==='user'? users.find(i=>i.id===id)||users[0] : type==='role'? {id, name:id, role:roles[0]} : type==='dict'? dict : logs.find(i=>i.id===id)||logs[0];
  const titleMap:Record<string,string>={ user:'用户详情', role:'角色详情', dict:'字典项详情', opLog:'操作日志详情', loginLog:'登录日志详情', dataPermission:'数据权限配置' };
  if (mode==='permission' || type==='dataPermission') return <>{contextHolder}<PageHeader title={type==='dataPermission'?'数据权限配置':'角色权限配置'} extra={<Button type='primary' onClick={()=>openAction('permission',data)}>保存权限</Button>} /><Card><Tabs items={[{key:'role',label:'角色权限配置',children:<Button onClick={()=>openAction('permission',data)}>打开权限配置 Drawer</Button>},{key:'data',label:'数据权限配置',children:<Form layout='vertical'><Form.Item label='可见部门'><Select mode='multiple' defaultValue={['咨询一部']} options={['咨询一部','文案部','签证部','运营部'].map(value=>({value}))}/></Form.Item><Form.Item label='可见业务'><Select mode='multiple' defaultValue={['线索','档案']} options={['线索','档案','申请','CMS','报表'].map(value=>({value}))}/></Form.Item></Form>}]} /></Card></>;
  if (mode==='edit') return <>{contextHolder}<PageHeader title={type==='user'?'用户编辑':'字典项编辑'} extra={<Space><Button onClick={()=>openAction('log',data)}>查看日志</Button><Button type='primary' onClick={()=>openAction('edit',data)}>保存</Button></Space>} /><Card><Form layout='vertical' initialValues={data}><Form.Item label='名称' name='name'><Input/></Form.Item><Form.Item label='手机号/编码' name={type==='user'?'mobile':'code'}><Input/></Form.Item><Form.Item label='角色/状态' name={type==='user'?'role':'status'}><Input/></Form.Item><Form.Item label='启用'><Switch defaultChecked={data.enabled ?? true}/></Form.Item></Form></Card></>;
  return <>{contextHolder}<PageHeader title={titleMap[type] || '设置详情'} extra={<Space><Button onClick={()=>openAction('edit',data)}>编辑</Button><Button onClick={()=>openAction('log',data)}>查看日志</Button><Button type='primary' onClick={()=>openAction('permission',data)}>配置权限</Button></Space>} /><Row gutter={[16,16]}><Col span={16}><Card><Descriptions bordered column={2} items={Object.entries(data).map(([label,value])=>({label,children:typeof value==='boolean'?<Tag color={value?'green':'red'}>{value?'启用':'停用'}</Tag>:String(value)}))}/></Card></Col><Col span={8}><Card title='操作轨迹'><Timeline items={[{children:'2026-05-06 09:30 查看详情'},{children:'2026-05-05 18:00 更新基础信息'},{children:'2026-05-04 11:30 调整权限范围'}]}/></Card></Col></Row></>;
}
