import { Alert, Button, Card, Col, Descriptions, Progress, Row, Space, Steps, Table, Tabs, Tag, Timeline } from 'antd';
import { useParams } from 'react-router-dom';
import { PageHeader, StatusTag } from '@/components';
import { appOverview, essayRows, materialRows, offers, riskCards, schoolRows, visaCases } from '@/mock/applications';
import { useEnterpriseActions } from '@/hooks/useEnterpriseActions';

const titleMap: Record<string, string> = { school:'选校规划详情', essay:'文书准备详情', online:'网申提交详情', offer:'Offer 跟进详情', visa:'签证办理详情', pre:'行前准备详情', risk:'风险提醒详情', material:'材料审核详情' };
export default function StageDetailPage(){
  const { stage='school' } = useParams(); const title = titleMap[stage] || '申请交付详情'; const {openAction, contextHolder}=useEnterpriseActions(title);
  return <>{contextHolder}<PageHeader title={title} extra={<Space><Button onClick={()=>openAction('file', appOverview)}>材料审核详情</Button><Button onClick={()=>openAction('log', appOverview)}>查看日志</Button><Button type='primary' onClick={()=>openAction('config', appOverview)}>节点配置</Button></Space>} />
    <Card className='mb12'><Descriptions column={3} items={[{label:'申请编号',children:appOverview.id},{label:'学生',children:appOverview.student},{label:'国家',children:appOverview.country},{label:'当前阶段',children:<StatusTag status={appOverview.stage}/>},{label:'负责人',children:appOverview.owner},{label:'目标院校',children:appOverview.targetSchools}]} /><Steps className='mt12' current={['school','essay','online','offer','visa','pre'].indexOf(stage)} items={['选校规划','文书准备','网申提交','Offer跟进','签证办理','行前准备'].map(title=>({title}))}/></Card>
    <Tabs items={[{key:'schools',label:'选校规划',children:<Table rowKey='id' dataSource={schoolRows} pagination={false} columns={[{title:'院校',dataIndex:'school'},{title:'专业',dataIndex:'major'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color='blue'>{v}</Tag>},{title:'截止时间',dataIndex:'deadline'},{title:'操作',render:(_:unknown,r:any)=><Button type='link' onClick={()=>openAction('view',r)}>查看详情</Button>}]} />},{key:'essay',label:'文书准备',children:<Table rowKey='id' dataSource={essayRows} pagination={false} columns={[{title:'文书',dataIndex:'name'},{title:'负责人',dataIndex:'owner'},{title:'状态',dataIndex:'status'},{title:'更新时间',dataIndex:'updated'},{title:'操作',render:(_:unknown,r:any)=><Button type='link' onClick={()=>openAction('edit',r)}>编辑详情</Button>}]} />},{key:'online',label:'网申提交',children:<Timeline items={[{children:'UCL 网申表单已完成 90%'},{children:'曼大申请费待支付'},{children:'爱丁堡项目推荐信等待上传'}]} />},{key:'offer',label:'Offer跟进',children:<Table rowKey='id' dataSource={offers} pagination={false} columns={[{title:'学校',dataIndex:'school'},{title:'专业',dataIndex:'major'},{title:'状态',dataIndex:'status'},{title:'操作',render:(_:unknown,r:any)=><Button type='link' onClick={()=>openAction('view',r)}>查看Offer</Button>}]} />},{key:'visa',label:'签证办理',children:<Table rowKey='id' dataSource={visaCases} pagination={false} columns={[{title:'学生',dataIndex:'student'},{title:'状态',dataIndex:'status'},{title:'材料进度',dataIndex:'progress',render:(v:number)=><Progress percent={v} size='small'/>},{title:'风险',dataIndex:'risk'}]} />},{key:'pre',label:'行前准备',children:<Row gutter={[16,16]}>{['住宿确认','机票预订','接机登记','行前说明会'].map(i=><Col span={6} key={i}><Card><h3>{i}</h3><Progress percent={75}/><Button className='mt12' onClick={()=>openAction('view',{name:i,status:'进行中'})}>查看详情</Button></Card></Col>)}</Row>},{key:'risk',label:'风险提醒',children:<Row gutter={[16,16]}>{riskCards.map(r=><Col span={12} key={r.title}><Alert type={r.level==='高'?'error':'warning'} showIcon message={`${r.title} · ${r.level}风险`} description={r.desc}/></Col>)}</Row>}]} />
  </>;
}
