import { Button, Card, Col, Descriptions, Form, Input, Row, Select, Space, Tabs, Tag } from 'antd';
import { useNavigate, useParams } from 'react-router-dom';
import { PageHeader } from '@/components';
import { articles, cases } from '@/mock/cms';
import { useEnterpriseActions } from '@/hooks/useEnterpriseActions';

export default function ContentDetailPage(){
  const { type='article', mode='detail', id='A01' } = useParams(); const nav=useNavigate(); const {openAction, contextHolder}=useEnterpriseActions('CMS内容');
  const isCase=type==='case'; const data=(isCase?cases:articles).find((i:any)=>i.id===id) || (isCase?cases[0]:articles[0]); const titleMap:Record<string,string>={detail:isCase?'案例详情页':'文章详情页',edit:isCase?'案例编辑页':'文章编辑页',preview:'文章预览页',country:'国家页详情',school:'院校页详情',home:'首页模块配置页',seo:'SEO配置页'};
  if (['country','school','home','seo'].includes(mode)) return <>{contextHolder}<PageHeader title={titleMap[mode]} extra={<Space><Button onClick={()=>openAction('log',data)}>查看日志</Button><Button type='primary' onClick={()=>openAction('config',data)}>保存配置</Button></Space>} /><Row gutter={[16,16]}><Col span={16}><Card><Tabs items={[{key:'basic',label:'基础配置',children:<Form layout='vertical'><Form.Item label='页面标题'><Input defaultValue={mode==='country'?'英国留学国家页':mode==='school'?'UCL 院校详情页':mode==='home'?'首页核心模块':'全站 SEO 默认配置'}/></Form.Item><Form.Item label='模块排序'><Select mode='multiple' defaultValue={['banner','advantages','schools']} options={['banner','advantages','schools','cases','articles','faq'].map(value=>({value}))}/></Form.Item><Form.Item label='摘要'><Input.TextArea rows={5} defaultValue='卡片化配置区，可维护 Banner、推荐内容、SEO 信息和发布状态。'/></Form.Item></Form>},{key:'preview',label:'配置预览',children:<Card className='preview-card'><h2>{titleMap[mode]}</h2><p>展示前台落地页头图、院校卡片、案例卡片、FAQ 与转化表单。</p></Card>}]} /></Card></Col><Col span={8}><Card title='发布状态'><Descriptions column={1} items={[{label:'状态',children:<Tag color='blue'>待发布</Tag>},{label:'最后保存',children:'2026-05-06 09:30'},{label:'负责人',children:'内容运营-林娜'}]}/><Button block className='mt12' onClick={()=>openAction('publish',data)}>发布</Button></Card></Col></Row></>;
  if (mode==='preview') return <>{contextHolder}<PageHeader title={titleMap[mode]} extra={<Space><Button onClick={()=>nav(`/cms/${isCase?'case':'article'}/edit/${id}`)}>编辑</Button><Button type='primary' onClick={()=>openAction('publish',data)}>发布</Button></Space>} /><Card className='preview-card'><Tag color='green'>预览模式</Tag><h1>{data.title}</h1><p>分类/国家：{(data as any).category || (data as any).country}</p><p>这里展示文章正文、案例背景、申请难点、录取结果、顾问点评和移动端排版预览。</p></Card></>;
  return <>{contextHolder}<PageHeader title={titleMap[mode]} extra={<Space><Button onClick={()=>openAction('preview',data)}>预览</Button><Button onClick={()=>openAction('log',data)}>查看日志</Button><Button type='primary' onClick={()=>openAction('publish',data)}>发布</Button></Space>} /><Card><Form layout='vertical' initialValues={data}><Form.Item label='标题' name='title'><Input/></Form.Item><Form.Item label={isCase?'国家':'分类'} name={isCase?'country':'category'}><Input/></Form.Item><Form.Item label='作者/顾问' name={isCase?'advisor':'author'}><Input/></Form.Item><Form.Item label='SEO标题'><Input defaultValue={`${data.title} - Tree Education`}/></Form.Item><Form.Item label='正文内容'><Input.TextArea rows={8} defaultValue='企业级 CMS 编辑器 Mock：支持图文内容、摘要、标签、推荐位、发布时间与 SEO 信息。'/></Form.Item></Form></Card></>;
}
